name: dex
description: A new Flutter project.

publish_to: "none"

version: 1.0.1+2

scripts:
  build: flutter pub run build_runner build
  build_delete: flutter pub run build_runner build --delete-conflicting-outputs
  clean: flutter pub run build_runner clean

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  pull_to_refresh: ^2.0.0
  path_provider: ^2.0.10
  hive: ^2.2.1
  dio: ^4.0.6
  flutter_mobx: ^2.0.6+1
  mobx: ^2.0.7+2
  flutter_modular: ^5.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  mobx_codegen: ^2.0.7
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
