name: dex
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

scripts:
  build: flutter pub run build_runner build
  build_delete: flutter pub run build_runner build --delete-conflicting-outputs
  clean: flutter pub run build_runner clean
  emulator: flutter emulators --launch Pixel_3a_API_30_x86

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cached_network_image: ^2.5.0
  pull_to_refresh: ^1.6.4
  path_provider: ^1.6.27
  hive: ^1.4.4+1
  dio: ^3.0.10
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+4
  flutter_modular: ^2.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  modular_codegen: ^2.1.0
  mobx_codegen: ^1.1.2
  build_runner: ^1.10.1
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
